version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
        - mysql
    tty: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    depends_on:
      - mysql
      - chrome
  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_PASSWORD: root  
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: root

    ports:
      - '4306:3306'
    volumes:
      -  ./mysql_data:/var/lib/mysql
      # - ./mysql-confd:/etc/mysql/conf.d      
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444
        
volumes:
  bundle:
  mysql_data: