import '../images/woman.png'
import '../images/lipstick.png'
import '../images/ladyicon.png'
import '../images/no_image.png'
import '../images/position.png'
import '../images/search1.png'
import '../images/sign_out.png'